Add validator methods for shopspring decimal
aarondl/oa3 pull request #17
Opened 2024-02-29 21:39 UTC by Sriram-bk

2024-03-01 15:21 UTC, aarondl requested changes

2024-03-01 15:21 UTC, aarondl commented on support/validation.go
> +func ValidateFormatDecimal(d decimal.Decimal) error {
This is weird. There should be runtime marshaling errors that happen if the decimal format is incorrect if you're using decimal.Decimal or `decimaltype=shopspring` for this generator. Probably if the generator is configured in a way where a decimal type is being specified this regex approach still makes sense.

2024-03-01 15:21 UTC, aarondl commented on templates/go/validate_field.tpl
> +{{- if and $.Object.Minimum (eq $.Object.Type "string") (eq (printf $.Object.Format) "decimal")}}
Missing a check on `decimaltype=shopspring` from the config.

2024-03-01 18:38 UTC, aarondl requested changes

2024-03-01 18:38 UTC, aarondl commented on templates/go/validate_field.tpl
> +{{- if and $.Object.Format (eq (printf $.Object.Format) "decimal") (eq $.Params.decimaltype "string")}}}
Is `string` a thing that gets set? I thought the default would be empty maybe?

2024-03-01 18:38 UTC, aarondl commented on templates/go/validate_field.tpl
> +{{- if and $.Object.Format (eq (printf $.Object.Format) "decimal") (eq $.Params.decimaltype "string")}}}
We should either change the default value to string, or check if this is empty instead? Not sure which is true, it *looks* like it's just empty.

2024-03-01 19:16 UTC, Sriram-bk commented on templates/go/validate_field.tpl
> +{{- if and $.Object.Format (eq (printf $.Object.Format) "decimal") (eq $.Params.decimaltype "string")}}}
Set the default for decimaltype to be string in the main method.

2024-03-02 00:14 UTC, aarondl requested changes
If we remove the nix files we're good to go.

2024-03-02 00:14 UTC, aarondl commented on flake.nix
> +{
Please remove

2024-03-02 00:26 UTC, Sriram-bk commented on flake.nix
> +{
🤦🏾‍♂️

2024-03-02 05:56 UTC, aarondl approved these changes

2024-03-02 05:57 UTC, merged